version: "3"

services:

  backend:
    build:
      context: .devcontainer/backend
      dockerfile: Dockerfile
    container_name: backend_fastapi_container
    ports:
      # fastapi
      - "8000:8000"
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - "./apps/backend:/home/vscode/workspace"
    tty: true
    stdin_open: true

  db:
    build:
      context: .devcontainer/database
      dockerfile: Dockerfile
    container_name: db_postgres_container
    ports:
      # postgres
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always
